steps:
  # Paso 1: Compilar la imagen usando KANIKO para activar la caché en la nube
  - name: 'gcr.io/kaniko-project/executor'
    args: [
      '--destination=southamerica-west1-docker.pkg.dev/$PROJECT_ID/todolist-repo/golang-backend:latest',
      '--cache=true',
      '--cache-dir=gs://${PROJECT_ID}-cloudbuild-cache/cache'
    ]

  # Paso 2: Desplegar la nueva versión en Cloud Run con control de tráfico
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'todolist-api',
      '--image', 'southamerica-west1-docker.pkg.dev/$PROJECT_ID/todolist-repo/golang-backend:latest',
      '--region', 'southamerica-west1',
      '--allow-unauthenticated',
      '--set-secrets=GCP_PROJECT_ID=PROJECT_ID_SECRET:latest',
      '--no-traffic',
      '--tag=canary'
    ]